/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "PagingModule"
 * 	found in "asn/Paging.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_PagingRecord_H_
#define	_PagingRecord_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PagingUE-Identity.h"
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum accessType {
	accessType_non3GPP	= 0
} e_accessType;

/* PagingRecord */
typedef struct PagingRecord {
	PagingUE_Identity_t	 ue_Identity;
	long	*accessType	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PagingRecord_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_accessType_3;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_PagingRecord;

#ifdef __cplusplus
}
#endif

#endif	/* _PagingRecord_H_ */
#include <asn_internal.h>
